### PR TITLE
Allow to specify custom name for Dockerfile

### PR DESCRIPTION
**Pull request by 7AC**
Right now the Dockerfile is hardcoded to be called `Dockerfile`, it is useful to be able to have multiple docker files in the same dir. For example in a Go repo it's useful to share the `vendor/` dir at the top of the repo.

The follow-up commit will be https://github.com/aristanetworks/official-images/commit/121516b7b0e6a33df2bd22ea24c29f29f4a70f9e

### CODE REVIEW

**Comment by 7AC** [comment]
If I'm reading this correctly codecov is now complaining only about pre-existing code:

https://codecov.io/gh/docker-library/go-dockerlibrary/src/5cfb31e65bb5a91577af5c89024d2667e6780086/manifest/rfc2822.go

**Comment by yosifkit** [comment]
Sorry for the delay. :bowing_man:
While this is not something that I envision us taking advantage of in official-images, it might be useful to anyone else that may use the `bashbrew` tool outside of official-images.  WDYT @tianon?

**Comment by 7AC** [comment]
@yosifkit that's exactly what we're doing: using Bashbrew to build images for our internal registry.

**Comment by 7AC** [comment]
@yosifkit can we bypass the false positives in codecov and merge this?

**Comment by tianon** [comment]
The PR over at https://github.com/docker-library/official-images will need a bit more, since it needs to also account for `diff-pr.sh`.  We'll also need to make changes in https://github.com/docker-library/docs and https://github.com/docker-library/oi-janky-groovy (at least), hopefully not too many other places.

**Edit:** making a list so we can keep better track:

- [x] https://github.com/docker-library/official-images
  - https://github.com/docker-library/official-images/pull/4980
  - [x] `bashbrew/go/src/*.go`
  - [x] `diff-pr.sh`
- [x] https://github.com/docker-library/docs
  - https://github.com/docker-library/docs/pull/1343
  - [x] `.template-helpers/generate-dockerfile-links-partial.tmpl`
- [x] https://github.com/docker-library/oi-janky-groovy
  - https://github.com/docker-library/oi-janky-groovy/pull/9
  - [x] `update.sh/target-pipeline.groovy`

**Comment by 7AC** [comment]
Thanks @tianon. Any pointers for what `diff-pr.sh` is supposed to do and how to test it? AFAICT `diff-pr.sh` needs no update because we still use `ArchDirectory()` alone to create archives:

https://github.com/aristanetworks/official-images/blob/master/bashbrew/go/src/bashbrew/cmd-build.go#L87

I opened https://github.com/docker-library/official-images/pull/4637, we can continue discussing there.

**Comment by tianon** [comment]
Updated PR for _just_ adding `File:` support to `bashbrew` itself and `diff-pr.sh` is at https://github.com/docker-library/official-images/pull/4980.

If that is accepted, I'll look to update https://github.com/docker-library/docs next (to ensure the documentation can handle non-standard `Dockerfile` paths too) and then hit up the `update.sh` pipeline bits afterwards.

**Pull request merged**
